sonar.projectKey=linty-hdl-designer
sonar.projectName=Linty HDL Designer
sonar.projectVersion=v1.2.3
sonar.sources=./src
sonar.hdl.topModule=plasma_3e
sonar.coverage.exclusions=**/*_tb.vhd,**/*_tb.sv,**/test/*,**/tests/*,**/Test/*,**/Tests/*,**/test_*,**/tests_*,**/Test_*,**/Tests_*
